# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'err.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(QtWidgets.QWidget):
    def __init__(self, error):
        super().__init__()
        self.setWindowIcon(QtGui.QIcon('resources/erricon.ico'))
        self.setObjectName("Dialog")
        self.resize(327, 239)
        self.setMinimumSize(QtCore.QSize(327, 239))
        self.setMaximumSize(QtCore.QSize(327, 239))
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(0, 0, 331, 241))
        self.label.setMinimumSize(QtCore.QSize(331, 241))
        self.label.setMaximumSize(QtCore.QSize(331, 16777215))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("resources/error.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(210, 110, 101, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.label_2.setText(f"error: {error}")

        self.pushButton.clicked.connect(self.onClick)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def onClick(self):
        self.close()

    def retranslateUi(self, ass):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Dialog", "Error"))
        self.pushButton.setText(_translate("Dialog", "Got It Fam"))
